# -*- coding: utf-8 -*-
"""ai_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1r5_bJ7kmdnL_jXNKQLeoyheGUdPCpe
"""

# -*- coding: utf-8 -*-
"""
Agent IA pour l'analyse conversationnelle des données TER
"""

import streamlit as st
import pandas as pd
from langchain_mistralai import ChatMistralAI
from langchain_core.tools import tool
from langchain.agents import AgentExecutor, create_tool_calling_agent
from langchain_core.prompts import ChatPromptTemplate
from config import Config

class TERAnalysisAgent:
    """Agent IA pour analyser les données TER"""

    def __init__(self, df: pd.DataFrame):
        self.df = df
        self.llm = ChatMistralAI(
            model=Config.MISTRAL_MODEL,
            mistral_api_key=Config.MISTRAL_API_KEY,
            temperature=0
        )
        self.agent_executor = self._create_agent()

    def _create_tools(self):
        """Crée les outils d'analyse disponibles pour l'agent"""

        df = self.df  # Référence locale pour les closures

        @tool
        def calculer_regularite_globale() -> str:
            """Calcule le taux de régularité global sur toutes les données."""
            if 'taux_regularite' in df.columns:
                avg = df['taux_regularite'].mean()
                return f"Le taux de régularité moyen global est de {avg:.2f}%"
            return "Colonne 'taux_regularite' non trouvée"

        @tool
        def regularite_par_region(region: str) -> str:
            """Calcule le taux de régularité pour une région spécifique."""
            if 'region' not in df.columns or 'taux_regularite' not in df.columns:
                return "Colonnes nécessaires non trouvées"

            df_region = df[df['region'].str.contains(region, case=False, na=False)]
            if df_region.empty:
                return f"Aucune donnée trouvée pour la région '{region}'"

            avg = df_region['taux_regularite'].mean()
            nb_records = len(df_region)
            return f"Région '{region}' : régularité moyenne de {avg:.2f}% sur {nb_records} enregistrements"

        @tool
        def top_regions_regulieres(n: int = 5) -> str:
            """Liste les N régions les plus régulières."""
            if 'region' not in df.columns or 'taux_regularite' not in df.columns:
                return "Colonnes nécessaires non trouvées"

            top = df.groupby('region')['taux_regularite'].mean().nlargest(n)
            result = f"Top {n} régions les plus régulières :\n"
            for i, (region, taux) in enumerate(top.items(), 1):
                result += f"{i}. {region} : {taux:.2f}%\n"
            return result

        @tool
        def pires_regions() -> str:
            """Liste les 5 régions avec la pire régularité."""
            if 'region' not in df.columns or 'taux_regularite' not in df.columns:
                return "Colonnes nécessaires non trouvées"

            bottom = df.groupby('region')['taux_regularite'].mean().nsmallest(5)
            result = "5 régions avec la pire régularité :\n"
            for i, (region, taux) in enumerate(bottom.items(), 1):
                result += f"{i}. {region} : {taux:.2f}%\n"
            return result

        @tool
        def statistiques_trains() -> str:
            """Donne des statistiques sur le nombre de trains."""
            stats = []

            if 'nombre_trains_prevus' in df.columns:
                total_prevus = df['nombre_trains_prevus'].sum()
                stats.append(f"Total trains prévus : {total_prevus:,.0f}")

            if 'nombre_trains_circules' in df.columns:
                total_circules = df['nombre_trains_circules'].sum()
                stats.append(f"Total trains circulés : {total_circules:,.0f}")

            if 'nombre_trains_supprimes' in df.columns:
                total_supprimes = df['nombre_trains_supprimes'].sum()
                stats.append(f"Total trains supprimés : {total_supprimes:,.0f}")

            if 'nombre_trains_retard' in df.columns:
                total_retards = df['nombre_trains_retard'].sum()
                stats.append(f"Total trains en retard : {total_retards:,.0f}")

            return "\n".join(stats) if stats else "Données de trains non disponibles"

        @tool
        def evolution_temporelle() -> str:
            """Analyse l'évolution de la régularité dans le temps."""
            if 'date' not in df.columns or 'taux_regularite' not in df.columns:
                return "Données temporelles non disponibles"

            # Premier et dernier mois
            df_sorted = df.sort_values('date')
            first_month = df_sorted.iloc[0]['taux_regularite']
            last_month = df_sorted.iloc[-1]['taux_regularite']
            evolution = last_month - first_month

            trend = "améliorée" if evolution > 0 else "dégradée"

            return (f"Évolution de la régularité :\n"
                   f"- Premier enregistrement : {first_month:.2f}%\n"
                   f"- Dernier enregistrement : {last_month:.2f}%\n"
                   f"- Tendance : {trend} ({evolution:+.2f} points)")

        return [
            calculer_regularite_globale,
            regularite_par_region,
            top_regions_regulieres,
            pires_regions,
            statistiques_trains,
            evolution_temporelle
        ]

    def _create_agent(self):
        """Crée l'agent conversationnel"""

        tools = self._create_tools()

        prompt = ChatPromptTemplate.from_messages([
            ("system", """Tu es un assistant expert en analyse ferroviaire pour la SNCF.
            Tu aides les data analysts à comprendre les données de ponctualité des TER.

            Utilise les outils disponibles pour répondre précisément aux questions.
            Réponds toujours en français de manière claire et structurée.
            Si une question nécessite plusieurs outils, utilise-les tous.
            Fournis des chiffres précis et des insights actionnables."""),
            ("human", "{input}"),
            ("placeholder", "{agent_scratchpad}"),
        ])

        agent = create_tool_calling_agent(self.llm, tools, prompt)

        return AgentExecutor(
            agent=agent,
            tools=tools,
            verbose=True,
            handle_parsing_errors=True,
            max_iterations=5
        )

    def ask(self, question: str) -> str:
        """Pose une question à l'agent"""
        try:
            response = self.agent_executor.invoke({"input": question})
            return response.get("output", "Désolé, je n'ai pas pu générer de réponse.")
        except Exception as e:
            return f"❌ Erreur : {str(e)}"