# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E39rmxfJogoJri2Cuam6fxNgh7DIrXdT
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from azure.storage.blob import BlobServiceClient
from langchain_experimental.agents.agent_toolkits import create_pandas_dataframe_agent
from langchain_mistralai import ChatMistralAI
import io

# --- CONFIGURATION DE LA PAGE ---
st.set_page_config(page_title="Train Data Assistant", layout="wide")
st.title("🚆 Assistant IA - Analyse Ferroviaire")

# --- RÉCUPÉRATION DES SECRETS ---
# Ces clés ne sont PAS écrites ici, elles sont lues depuis les paramètres Streamlit Cloud
try:
    AZURE_CONN = st.secrets["AZURE_STORAGE_CONNECTION_STRING"]
    MISTRAL_KEY = st.secrets["MISTRAL_API_KEY"]
except KeyError:
    st.error("⚠️ Clés de configuration manquantes dans les Secrets Streamlit.")
    st.stop()

# --- CHARGEMENT DES DONNÉES DEPUIS AZURE ---
@st.cache_data(show_spinner=False)
def load_data_from_azure():
    try:
        service_client = BlobServiceClient.from_connection_string(AZURE_CONN)
        # /!\ REMPLACE 'mon-container' ET 'data.csv' PAR TES VRAIS NOMS /!\
        blob_client = service_client.get_blob_client(container="ztacontainer", blob="otp_transformed.xlsx")

        stream = blob_client.download_blob().readall()
        data = pd.read_excel(io.BytesIO(stream))
        return data
    except Exception as e:
        st.error(f"Erreur de connexion Azure : {e}")
        return None

df = load_data_from_azure()

if df is not None:
    # --- INITIALISATION DE L'AGENT ---
    llm = ChatMistralAI(
        model="mistral-small-latest",
        mistral_api_key=MISTRAL_KEY,
        temperature=0
    )

    # Prefix pour forcer l'IA à être rigoureuse et ne pas bugger le parser
    PREFIX = "You are a data expert. Use the pandas dataframe 'df'. If you create a chart, use matplotlib and conclude with 'Final Answer: Done.'"
    if len(df) > 10000:
        df_sample = df.sample(n=10000, random_state=42)
        st.warning("Utilisation d'un échantillon du DataFrame pour accélérer l'analyse.")
    else:
        df_sample = df
    
    # Ensuite, utilise df_sample pour l'agent
    agent = create_pandas_dataframe_agent(
        llm,
        df_sample, # ✅ Utilise l'échantillon ici
        verbose=True,
        allow_dangerous_code=True,
        handle_parsing_errors=False,
        prefix=PREFIX
    )
    

    # --- INTERFACE UTILISATEUR ---
    st.write("### Aperçu des données Azure :")
    st.dataframe(df.head(5))

    query = st.text_input("Posez une question sur vos trains (ex: 'Fais un bar chart des retards') :")

import traceback

import traceback
import requests

if query:
    with st.spinner("L'IA analyse et génère le visuel..."):
        response = None
        try:
            response = agent.invoke({"input": query})
        except Exception as e:
            # Cas rate limit Mistral
            if "rate limit exceeded" in str(e).lower() or "429" in str(e):
                st.error("L'API Mistral a atteint sa limite de requêtes (429). "
                         "Réessaie dans quelques instants ou réduis la fréquence des questions.")
            else:
                st.warning("L'agent a rencontré une erreur (parsing ou autre). "
                           "Le code Python a peut‑être été exécuté malgré tout.")
                st.text(str(e)[:500])

        # Si la requête a quand même réussi
        if isinstance(response, dict):
            st.markdown("#### Réponse de l'assistant :")
            st.write(response.get("output", response))

        # Affichage du graphique si présent
        if plt.get_fignums():
            st.pyplot(plt.gcf())
            plt.clf()
else:
    st.warning("Impossible de charger le DataFrame. Vérifiez vos accès Azure.")
