# -*- coding: utf-8 -*-
"""Untitled91.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E39rmxfJogoJri2Cuam6fxNgh7DIrXdT
"""

import streamlit as st
import pandas as pd
# ... (tes imports Azure et LangChain)

st.title("🚆 Assistant IA - Trafic Ferroviaire")

# Champ de saisie pour l'utilisateur
user_question = st.text_input("Posez une question sur les retards ou demandez un graphique :")

if user_question:
    with st.spinner("L'IA analyse les données sur Azure..."):
        # Ici on appelle ton agent.invoke()
        response = agent.invoke(user_question)
        st.write(response["output"])
        # Les graphiques s'afficheront automatiquement si l'agent utilise plt.show()