# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hYItS18PLQCpiQ-SmpmsADcKMFhS_FxS

<a href="https://colab.research.google.com/github/ZoubirCHATTI/ai_assistant/blob/main/app.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
"""



# -*- coding: utf-8 -*-
# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from azure.storage.blob import BlobServiceClient
from langchain.agents import initialize_agent, AgentType
from langchain_mistralai import ChatMistralAI
from langchain.tools import Tool
import io
import traceback

# --- CONFIGURATION DE LA PAGE ---
st.set_page_config(page_title="Train Data Assistant", layout="wide")
st.title("🚆 Assistant IA - Analyse Ferroviaire")

# --- RÉCUPÉRATION DES SECRETS ---
try:
    AZURE_CONN = st.secrets["AZURE_STORAGE_CONNECTION_STRING"]
    MISTRAL_KEY = st.secrets["MISTRAL_API_KEY"]
except KeyError:
    st.error("⚠️ Clés de configuration manquantes dans les Secrets Streamlit.")
    st.stop()

# --- CHARGEMENT DES DONNÉES ---
@st.cache_data(show_spinner="Chargement des données depuis Azure...")
def load_data_from_azure():
    try:
        service_client = BlobServiceClient.from_connection_string(AZURE_CONN)
        blob_client = service_client.get_blob_client(container="ztacontainer", blob="otp_transformed.xlsx")
        stream = blob_client.download_blob().readall()
        data = pd.read_excel(io.BytesIO(stream))
        return data
    except Exception as e:
        st.error(f"Erreur lors du chargement depuis Azure : {e}")
        return None

df = load_data_from_azure()

if df is not None:
    # Échantillonnage si nécessaire
    if len(df) > 10000:
        df_sample = df.sample(n=10000, random_state=42)
        st.info(f"📊 Échantillon de 10 000 lignes utilisé (sur {len(df)})")
    else:
        df_sample = df

    # --- FONCTIONS MÉTIER ---
    def ponctualite_par_direction(direction: str) -> str:
        """Calcule le taux de ponctualité pour une direction ('N' ou 'S')"""
        direction = direction.strip().upper()
        if direction not in ['N', 'S']:
            return "Erreur : direction doit être 'N' ou 'S'"
        
        df_dir = df_sample[df_sample['direction'].str.upper() == direction]
        if df_dir.empty:
            return f"Aucune donnée pour la direction {direction}"
        
        total = len(df_dir)
        a_l_heure = len(df_dir[df_dir['is_delayed'] == 0])
        taux = (a_l_heure / total) * 100
        
        return f"Direction {direction} : {total} trains, {a_l_heure} à l'heure, ponctualité = {taux:.2f}%"

    def heures_critiques(input_text: str = "") -> str:
        """Identifie les heures avec le plus de retards"""
        df_retards = df_sample[df_sample['is_delayed'] == 1]
        if df_retards.empty:
            return "Aucun train en retard"
        
        top_heures = df_retards['hour'].value_counts().nlargest(3)
        result = "Top 3 heures avec le plus de retards :\n"
        for heure, count in top_heures.items():
            result += f"- {heure}h : {count} trains\n"
        return result

    def trains_critiques(input_text: str = "") -> str:
        """Liste les 5 trains avec les plus longs retards"""
        top_trains = df_sample.nlargest(5, 'delay_minutes')
        result = "Top 5 trains avec les plus longs retards :\n"
        for idx, row in top_trains.iterrows():
            result += f"- Train {row['train_id']} : {row['delay_minutes']} min\n"
        return result

    def stats_globales(input_text: str = "") -> str:
        """Statistiques générales sur la ponctualité"""
        total = len(df_sample)
        retards = df_sample['is_delayed'].sum()
        taux_ponctualite = ((total - retards) / total) * 100
        retard_moyen = df_sample[df_sample['is_delayed'] == 1]['delay_minutes'].mean()
        
        return (f"📊 Statistiques globales :\n"
                f"- Total : {total} trains\n"
                f"- En retard : {retards} ({100*retards/total:.1f}%)\n"
                f"- Ponctualité : {taux_ponctualite:.2f}%\n"
                f"- Retard moyen : {retard_moyen:.1f} min")

    # --- CRÉATION DES TOOLS ---
    tools = [
        Tool(
            name="Ponctualite_Direction",
            func=ponctualite_par_direction,
            description="Calcule la ponctualité pour une direction. Input requis : 'N' ou 'S'"
        ),
        Tool(
            name="Heures_Critiques",
            func=heures_critiques,
            description="Identifie les heures avec le plus de retards. Pas d'input requis."
        ),
        Tool(
            name="Trains_Critiques",
            func=trains_critiques,
            description="Liste les trains avec les plus longs retards. Pas d'input requis."
        ),
        Tool(
            name="Statistiques_Globales",
            func=stats_globales,
            description="Donne les statistiques générales de ponctualité. Pas d'input requis."
        )
    ]

    # --- INITIALISATION LLM ET AGENT ---
    llm = ChatMistralAI(
        model="mistral-small-latest",
        mistral_api_key=MISTRAL_KEY,
        temperature=0
    )

    agent = initialize_agent(
        tools=tools,
        llm=llm,
        agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
        verbose=True,
        handle_parsing_errors=True,
        max_iterations=3
    )

    # --- INTERFACE ---
    st.write("### 📋 Aperçu des données")
    st.dataframe(df_sample.head(5))
    
    st.write("### 💬 Posez votre question")
    st.markdown("""
    **Exemples :**
    - Quelle est la ponctualité de la direction N ?
    - Quelles sont les heures critiques ?
    - Donne-moi les statistiques globales
    - Quels sont les trains les plus en retard ?
    """)

    query = st.text_input("Votre question :", key="query_input")

    if query:
        with st.spinner("🤔 L'IA réfléchit..."):
            try:
                response = agent.invoke({"input": query})
                st.markdown("#### ✅ Réponse :")
                st.success(response.get("output", "Pas de réponse"))
                
            except Exception as e:
                error_str = str(e)
                if "429" in error_str or "rate limit" in error_str.lower():
                    st.error("⏳ Limite de requêtes Mistral atteinte. Attendez quelques minutes.")
                else:
                    st.error("❌ Erreur lors du traitement")
                    with st.expander("Détails"):
                        st.code(traceback.format_exc())

    # --- BOUTONS RAPIDES ---
    st.write("---")
    st.write("### ⚡ Actions rapides")
    
    col1, col2, col3, col4 = st.columns(4)
    
    with col1:
        if st.button("📊 Stats"):
            st.info(stats_globales())
    
    with col2:
        if st.button("🔴 Heures critiques"):
            st.warning(heures_critiques())
    
    with col3:
        if st.button("🚂 Top retards"):
            st.error(trains_critiques())
    
    with col4:
        if st.button("📈 Direction N"):
            st.success(ponctualite_par_direction("N"))

else:
    st.error("❌ Impossible de charger les données depuis Azure")
    
    with col3:
        if st.button("🚂 Top 5 retards"):
            st.error(trains_les_plus_critiques())

else:
    st.warning("Impossible de charger le DataFrame. Vérifiez votre connexion Azure.")
