{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNsruYkB8M0/h7N0B0qhmth",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/ZoubirCHATTI/ai_assistant/blob/main/assistant1.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# -*- coding: utf-8 -*-\n",
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "from azure.storage.blob import BlobServiceClient\n",
        "from langchain_experimental.agents.agent_toolkits import create_pandas_dataframe_agent\n",
        "from langchain.agents import AgentExecutor, create_react_agent\n",
        "from langchain_mistralai import ChatMistralAI\n",
        "from langchain.tools import Tool\n",
        "from langchain import hub\n",
        "import io\n",
        "import traceback\n",
        "import requests\n",
        "\n",
        "# --- CONFIGURATION DE LA PAGE ---\n",
        "st.set_page_config(page_title=\"Train Data Assistant\", layout=\"wide\")\n",
        "st.title(\"🚆 Assistant IA - Analyse Ferroviaire\")\n",
        "\n",
        "# --- RÉCUPÉRATION DES SECRETS ---\n",
        "try:\n",
        "    AZURE_CONN = st.secrets[\"AZURE_STORAGE_CONNECTION_STRING\"]\n",
        "    MISTRAL_KEY = st.secrets[\"MISTRAL_API_KEY\"]\n",
        "except KeyError:\n",
        "    st.error(\"⚠️ Clés de configuration manquantes dans les Secrets Streamlit.\")\n",
        "    st.info(\"Veuillez configurer AZURE_STORAGE_CONNECTION_STRING et MISTRAL_API_KEY.\")\n",
        "    st.stop()\n",
        "\n",
        "# --- CHARGEMENT ET CACHE DES DONNÉES ---\n",
        "@st.cache_data(show_spinner=\"Connexion à Azure et chargement des données...\")\n",
        "def load_data_from_azure():\n",
        "    try:\n",
        "        service_client = BlobServiceClient.from_connection_string(AZURE_CONN)\n",
        "        blob_client = service_client.get_blob_client(container=\"ztacontainer\", blob=\"otp_transformed.xlsx\")\n",
        "        stream = blob_client.download_blob().readall()\n",
        "        data = pd.read_excel(io.BytesIO(stream))\n",
        "        return data\n",
        "    except Exception as e:\n",
        "        st.error(f\"Erreur de connexion ou de chargement depuis Azure : {e}\")\n",
        "        return None\n",
        "\n",
        "df = load_data_from_azure()\n",
        "\n",
        "if df is not None:\n",
        "    # --- PRÉPARATION DU DATAFRAME POUR L'ANALYSE ---\n",
        "    # Échantillonner si le DataFrame est trop grand pour accélérer les requêtes\n",
        "    if len(df) > 10000:\n",
        "        df_sample = df.sample(n=10000, random_state=42)\n",
        "        st.warning(f\"Utilisation d'un échantillon de 10,000 lignes (sur {len(df)}) pour accélérer l'analyse.\")\n",
        "    else:\n",
        "        df_sample = df\n",
        "\n",
        "    # --- DÉFINITION DES FONCTIONS MÉTIER (OUTILS PERSONNALISÉS) ---\n",
        "    def create_ferroviaire_tools(dataframe):\n",
        "        \"\"\"Crée une liste d'outils personnalisés pour l'analyse ferroviaire.\"\"\"\n",
        "\n",
        "        @Tool\n",
        "        def ponctualite_par_direction(direction: str) -> str:\n",
        "            \"\"\"\n",
        "            Calcule le taux de ponctualité pour une direction spécifique ('N' ou 'S').\n",
        "            Utilise cet outil pour répondre à des questions comme 'quelle est la ponctualité de la direction N ?'.\n",
        "            \"\"\"\n",
        "            if direction.upper() not in ['N', 'S']:\n",
        "                return \"Erreur : La direction doit être 'N' ou 'S'.\"\n",
        "\n",
        "            df_dir = dataframe[dataframe['direction'].str.upper() == direction.upper()]\n",
        "            if df_dir.empty:\n",
        "                return f\"Aucune donnée trouvée pour la direction {direction}.\"\n",
        "\n",
        "            total_trains = len(df_dir)\n",
        "            trains_a_l_heure = len(df_dir[df_dir['is_delayed'] == 0])\n",
        "            taux_ponctualite = (trains_a_l_heure / total_trains) * 100 if total_trains > 0 else 0\n",
        "\n",
        "            return (f\"Pour la direction {direction.upper()} : \\n\"\n",
        "                    f\"- {total_trains} trains au total.\\n\"\n",
        "                    f\"- {trains_a_l_heure} trains à l'heure.\\n\"\n",
        "                    f\"- Taux de ponctualité : {taux_ponctualite:.2f}%.\")\n",
        "\n",
        "        @Tool\n",
        "        def heures_avec_le_plus_de_retards() -> str:\n",
        "            \"\"\"\n",
        "            Identifie les 3 heures de la journée où il y a le plus de trains en retard.\n",
        "            Utilise cet outil pour des questions comme 'quelles sont les pires heures ?' ou 'quand y a-t-il le plus de retards ?'.\n",
        "            \"\"\"\n",
        "            df_retards = dataframe[dataframe['is_delayed'] == 1]\n",
        "            if df_retards.empty:\n",
        "                return \"Bonne nouvelle ! Aucun train en retard n'a été trouvé.\"\n",
        "\n",
        "            top_heures = df_retards['hour'].value_counts().nlargest(3)\n",
        "            result = \"Les 3 heures avec le plus de retards sont :\\n\"\n",
        "            for heure, count in top_heures.items():\n",
        "                result += f\"- {heure}h00 : {count} trains en retard.\\n\"\n",
        "            return result\n",
        "\n",
        "        @Tool\n",
        "        def trains_les_plus_critiques() -> str:\n",
        "            \"\"\"\n",
        "            Liste les 5 trains ayant accumulé le plus de retard en minutes.\n",
        "            Utile pour identifier les 'pires trains' ou les 'retards les plus longs'.\n",
        "            \"\"\"\n",
        "            top_trains = dataframe.sort_values(by='delay_minutes', ascending=False).nlargest(5, 'delay_minutes')\n",
        "            result = \"Les 5 trains avec les plus longs retards sont :\\n\"\n",
        "            for _, row in top_trains.iterrows():\n",
        "                result += f\"- Train ID {row['train_id']} : {row['delay_minutes']} minutes de retard le {row['date']}.\\n\"\n",
        "            return result\n",
        "\n",
        "        return [ponctualite_par_direction, heures_avec_le_plus_de_retards, trains_les_plus_critiques]\n",
        "\n",
        "    # --- INITIALISATION DU LLM ET DES AGENTS ---\n",
        "    llm = ChatMistralAI(model=\"mistral-small-latest\", mistral_api_key=MISTRAL_KEY, temperature=0)\n",
        "\n",
        "    # 1. Créer l'agent Pandas pour l'analyse générale du DataFrame\n",
        "    pandas_agent = create_pandas_dataframe_agent(\n",
        "        llm,\n",
        "        df_sample,\n",
        "        verbose=True,\n",
        "        allow_dangerous_code=True,\n",
        "        handle_parsing_errors=True # Gère mieux les erreurs de formatage du LLM\n",
        "    )\n",
        "\n",
        "    # 2. Transformer l'agent Pandas en un seul \"super-outil\"\n",
        "    pandas_tool = Tool(\n",
        "        name=\"Analyseur de DataFrame Pandas\",\n",
        "        func=pandas_agent.invoke,\n",
        "        description=\"\"\"\n",
        "        Utilise cet outil pour toute question générale sur les données des trains.\n",
        "        Il peut répondre à des questions sur les statistiques, filtrer des données, et même créer des graphiques (bar charts, line charts, etc.).\n",
        "        Exemples de questions : 'combien de trains au total ?', 'fais-moi un bar chart des retards par jour de la semaine', 'quel est le retard moyen ?'.\n",
        "        \"\"\"\n",
        "    )\n",
        "\n",
        "    # 3. Rassembler tous les outils : nos outils métier + le super-outil Pandas\n",
        "    outils_personnalises = create_ferroviaire_tools(df_sample)\n",
        "    tous_les_outils = outils_personnalises + [pandas_tool]\n",
        "\n",
        "    # 4. Créer l'agent final qui orchestre tous les outils\n",
        "    # On récupère un prompt standard optimisé pour ce type d'agent\n",
        "    prompt = hub.pull(\"hwchase17/react\")\n",
        "    agent_final = create_react_agent(llm, tous_les_outils, prompt)\n",
        "    agent_executor = AgentExecutor(agent=agent_final, tools=tous_les_outils, verbose=True, handle_parsing_errors=True)\n",
        "\n",
        "    # --- INTERFACE UTILISATEUR ---\n",
        "    st.info(\"Assistant prêt ! Posez une question sur vos données.\")\n",
        "    st.write(\"Exemples de questions :\")\n",
        "    st.markdown(\"\"\"\n",
        "    - *Quelle est la ponctualité pour la direction S ?* (utilise un outil métier)\n",
        "    - *Quelles sont les heures avec le plus de retards ?* (utilise un outil métier)\n",
        "    - *Montre-moi un bar chart des retards par jour de la semaine.* (utilise l'analyseur Pandas)\n",
        "    - *Combien y a-t-il de trains uniques ?* (utilise l'analyseur Pandas)\n",
        "    \"\"\")\n",
        "\n",
        "    query = st.text_input(\"Posez votre question ici :\", key=\"main_query\")\n",
        "\n",
        "    if query:\n",
        "        with st.spinner(\"L'IA réfléchit et choisit le meilleur outil...\"):\n",
        "            response = None\n",
        "            try:\n",
        "                # On invoque l'agent orchestrateur\n",
        "                response = agent_executor.invoke({\"input\": query})\n",
        "\n",
        "                st.markdown(\"#### Réponse de l'assistant :\")\n",
        "                st.write(response.get(\"output\", \"Désolé, je n'ai pas pu formuler de réponse claire.\"))\n",
        "\n",
        "            except requests.exceptions.HTTPError as e:\n",
        "                if e.response.status_code == 429:\n",
        "                    st.error(\"⏳ Erreur 429 : Trop de requêtes envoyées à l'API Mistral. Veuillez attendre un moment avant de réessayer.\")\n",
        "                else:\n",
        "                    st.error(f\"Erreur de connexion avec l'API : {e}\")\n",
        "            except Exception as e:\n",
        "                st.error(\"Oups, une erreur inattendue est survenue.\")\n",
        "                st.code(traceback.format_exc())\n",
        "\n",
        "            # Afficher le graphique s'il en a généré un via l'agent Pandas\n",
        "            if plt.get_fignums():\n",
        "                st.success(\"Un graphique a été généré :\")\n",
        "                st.pyplot(plt.gcf())\n",
        "                plt.clf() # Nettoyer la figure pour la prochaine requête\n",
        "\n",
        "else:\n",
        "    st.warning(\"Impossible de charger le DataFrame. L'application ne peut pas démarrer.\")\n",
        "    st.info(\"Vérifiez votre chaîne de connexion Azure et le nom du conteneur/fichier.\")"
      ],
      "metadata": {
        "id": "sSj6Y9f11T9O"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}