# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hYItS18PLQCpiQ-SmpmsADcKMFhS_FxS

<a href="https://colab.research.google.com/github/ZoubirCHATTI/ai_assistant/blob/main/app.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
"""



# -*- coding: utf-8 -*-
# -*- coding: utf-8 -*-
# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from azure.storage.blob import BlobServiceClient
from langchain_mistralai import ChatMistralAI
from langchain.tools import Tool
from langchain.agents import AgentExecutor, create_tool_calling_agent # <-- NOUVEAUX IMPORTS
from langchain_core.prompts import ChatPromptTemplate # <-- NOUVEL IMPORT
import io
import traceback

# --- CONFIGURATION ---
st.set_page_config(page_title="Train Data Assistant", layout="wide")
st.title("🚆 Assistant IA - Analyse Ferroviaire")

# --- SECRETS ---
try:
    AZURE_CONN = st.secrets["AZURE_STORAGE_CONNECTION_STRING"]
    MISTRAL_KEY = st.secrets["MISTRAL_API_KEY"]
except KeyError:
    st.error("⚠️ Clés manquantes dans les Secrets Streamlit.")
    st.stop()

# --- CHARGEMENT DONNÉES ---
@st.cache_data(show_spinner="Chargement...")
def load_data_from_azure():
    try:
        service_client = BlobServiceClient.from_connection_string(AZURE_CONN)
        blob_client = service_client.get_blob_client(container="ztacontainer", blob="otp_transformed.xlsx")
        stream = blob_client.download_blob().readall()
        return pd.read_excel(io.BytesIO(stream))
    except Exception as e:
        st.error(f"Erreur Azure : {e}")
        return None

df = load_data_from_azure()

if df is not None:
    if len(df) > 10000:
        df_sample = df.sample(n=10000, random_state=42)
        st.info(f"Échantillon de 10 000 lignes sur {len(df)}")
    else:
        df_sample = df

    # --- FONCTIONS MÉTIER ---
    def ponctualite_par_direction(direction: str) -> str:
        direction = direction.strip().upper()
        if direction not in ['N', 'S']:
            return "Erreur : direction doit être 'N' ou 'S'"
        df_dir = df_sample[df_sample['direction'].str.upper() == direction]
        if df_dir.empty:
            return f"Aucune donnée pour {direction}"
        total = len(df_dir)
        a_l_heure = len(df_dir[df_dir['is_delayed'] == 0])
        taux = (a_l_heure / total) * 100
        return f"Direction {direction} : {total} trains, {a_l_heure} à l'heure, ponctualité = {taux:.2f}%"

    def heures_critiques(txt: str = "") -> str:
        df_retards = df_sample[df_sample['is_delayed'] == 1]
        if df_retards.empty:
            return "Aucun retard"
        top = df_retards['hour'].value_counts().nlargest(3)
        result = "Top 3 heures critiques :\n"
        for h, c in top.items():
            result += f"- {h}h : {c} trains\n"
        return result

    def trains_critiques(txt: str = "") -> str:
        top = df_sample.nlargest(5, 'delay_minutes')
        result = "Top 5 retards :\n"
        for _, r in top.iterrows():
            result += f"- Train {r['train_id']} : {r['delay_minutes']} min\n"
        return result

    def stats_globales(txt: str = "") -> str:
        total = len(df_sample)
        retards = df_sample['is_delayed'].sum()
        taux = ((total - retards) / total) * 100
        retard_moy = df_sample[df_sample['is_delayed'] == 1]['delay_minutes'].mean()
        return (f"Stats :\n- Total : {total} trains\n- Retards : {retards} ({100*retards/total:.1f}%)\n"
                f"- Ponctualité : {taux:.2f}%\n- Retard moyen : {retard_moy:.1f} min")

    # --- TOOLS ---
    tools = [
        Tool(name="Ponctualite_Direction", func=ponctualite_par_direction,
             description="Calcule la ponctualité pour une direction donnée. L'input doit être 'N' ou 'S'."),
        Tool(name="Heures_Critiques", func=heures_critiques,
             description="Identifie les heures de la journée avec le plus de retards. Aucun input spécifique requis."),
        Tool(name="Trains_Critiques", func=trains_critiques,
             description="Liste les 5 trains ayant accumulé le plus de retard en minutes. Aucun input spécifique requis."),
        Tool(name="Statistiques_Globales", func=stats_globales,
             description="Fournit les statistiques générales de ponctualité pour l'ensemble des trains. Aucun input spécifique requis.")
    ]

    # --- AGENT ---
    llm = ChatMistralAI(model="mistral-small-latest", mistral_api_key=MISTRAL_KEY, temperature=0)

    # 1. Créer le Prompt
    prompt = ChatPromptTemplate.from_messages(
        [
            ("system", "Tu es un assistant expert en analyse ferroviaire. Utilise les outils pour répondre aux questions. Réponds toujours en français."),
            ("human", "{input}"),
            ("placeholder", "{agent_scratchpad}"), # Nécessaire pour le fonctionnement interne de l'agent
        ]
    )

    # 2. Créer l'Agent (logique qui choisit les outils)
    agent = create_tool_calling_agent(llm, tools, prompt)

    # 3. Créer l'Executor (qui exécute l'agent et les outils)
    agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)

    # --- UI ---
    st.write("### 📋 Aperçu")
    st.dataframe(df_sample.head(5))
    
    st.write("### 💬 Question")
    st.markdown("**Exemples :** *Ponctualité direction N ?* • *Heures critiques ?* • *Stats globales ?*")

    query = st.text_input("Votre question :", key="q")

    if query:
        with st.spinner("Réflexion..."):
            try:
                # Utiliser l'agent_executor pour invoquer
                response = agent_executor.invoke({"input": query}) 
                st.markdown("#### ✅ Réponse")
                st.success(response.get("output", "Pas de réponse"))
                
            except Exception as e:
                if "429" in str(e) or "rate limit" in str(e).lower():
                    st.error("⏳ Rate limit Mistral atteint")
                else:
                    st.error("❌ Erreur")
                    with st.expander("Détails"):
                        st.code(traceback.format_exc())

    # --- BOUTONS ---
    st.write("---")
    st.write("### ⚡ Actions rapides")
    
    c1, c2, c3, c4 = st.columns(4)
    with c1:
        if st.button("📊 Stats"):
            st.info(stats_globales())
    with c2:
        if st.button("🔴 Heures"):
            st.warning(heures_critiques())
    with c3:
        if st.button("🚂 Retards"):
            st.error(trains_critiques())
    with c4:
        if st.button("📈 Dir N"):
            st.success(ponctualite_par_direction("N"))
else:
    st.error("❌ Impossible de charger les données")
    
