# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1r5_bJ7kmdnL_jXNKQLeoyheGUdPCpe
"""

# -*- coding: utf-8 -*-
"""
Configuration centralisée pour l'Assistant IA TER
"""

import streamlit as st

class Config:
    """Configuration de l'application"""

    # Azure Storage
    AZURE_CONNECTION_STRING = st.secrets.get("AZURE_STORAGE_CONNECTION_STRING", "")
    AZURE_CONTAINER_NAME = st.secrets.get("AZURE_CONTAINER_NAME", "ztacontainer")
    AZURE_BLOB_NAME = st.secrets.get("AZURE_BLOB_NAME", "ter_ponctualite_2024_2025.csv")

    # Mistral AI
    MISTRAL_API_KEY = st.secrets.get("MISTRAL_API_KEY", "")
    MISTRAL_MODEL = "mistral-small-latest"

    # Configuration de l'app
    APP_TITLE = "🚆 Assistant IA - Analyse TER SNCF"
    APP_ICON = "🚆"
    LAYOUT = "wide"

    # Colonnes attendues dans le dataset TER (à adapter selon tes vraies colonnes)
    EXPECTED_COLUMNS = {
        'date': 'Date',
        'annee': 'Année',
        'mois': 'Mois',
        'region': 'Région',
        'nombre_trains_prevus': 'Trains prévus',
        'nombre_trains_circules': 'Trains circulés',
        'nombre_trains_a_l_heure': 'Trains à l\'heure',
        'nombre_trains_retard': 'Trains en retard',
        'nombre_trains_supprimes': 'Trains supprimés',
        'taux_regularite': 'Taux de régularité (%)'
    }

    # Seuils d'alerte
    SEUIL_REGULARITE_CRITIQUE = 85.0  # % en dessous duquel c'est critique
    SEUIL_REGULARITE_NORMAL = 92.0    # % au-dessus duquel c'est bon

# Vérification des secrets au démarrage
def check_config():
    """Vérifie que toutes les configurations sont présentes"""
    missing = []

    if not Config.AZURE_CONNECTION_STRING:
        missing.append("AZURE_STORAGE_CONNECTION_STRING")
    if not Config.MISTRAL_API_KEY:
        missing.append("MISTRAL_API_KEY")

    if missing:
        st.error(f"⚠️ Configuration manquante : {', '.join(missing)}")
        st.info("💡 Configurez ces secrets dans les paramètres Streamlit Cloud ou dans .streamlit/secrets.toml")
        st.stop()
