# -*- coding: utf-8 -*-
"""data_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1r5_bJ7kmdnL_jXNKQLeoyheGUdPCpe
"""

# -*- coding: utf-8 -*-
"""
Module de chargement des données depuis Azure Blob Storage
"""

import streamlit as st
import pandas as pd
import io
from azure.storage.blob import BlobServiceClient
from config import Config



class TERDataLoader:
    """Classe pour charger et préparer les données TER"""
    
    @st.cache_data(ttl=3600, show_spinner="📥 Chargement des données depuis Azure...")
    def load_data_from_azure():
        """
        Charge les données TER depuis Azure Blob Storage
        Cache les données pendant 1 heure
        """
        try:
            # Connexion à Azure
            service_client = BlobServiceClient.from_connection_string(
                Config.AZURE_CONNECTION_STRING
            )
    
            # Récupération du blob
            blob_client = service_client.get_blob_client(
                container=Config.AZURE_CONTAINER_NAME,
                blob=Config.AZURE_BLOB_NAME
            )
    
            # Téléchargement
            stream = blob_client.download_blob().readall()
    
            # Lecture selon le format
            if Config.AZURE_BLOB_NAME.endswith('.xlsx'):
                df = pd.read_excel(io.BytesIO(stream))
            elif Config.AZURE_BLOB_NAME.endswith('.csv'):
                df = pd.read_csv(io.BytesIO(stream))
            else:
                st.error("❌ Format de fichier non supporté. Utilisez .xlsx ou .csv")
                return None
    
            # Nettoyage de base
            df = clean_data(df)
    
            return df
    
        except Exception as e:
            st.error(f"❌ Erreur lors du chargement depuis Azure : {e}")
            return None
    
    def clean_data(df):
        """Nettoie et prépare les données"""
    
        # Conversion des dates
        date_columns = ['date', 'Date', 'DATE']
        for col in date_columns:
            if col in df.columns:
                df[col] = pd.to_datetime(df[col], errors='coerce')
                break
    
        # Standardisation des noms de colonnes (minuscules, sans espaces)
        df.columns = df.columns.str.lower().str.replace(' ', '_').str.replace("'", '')
    
        # Suppression des doublons
        df = df.drop_duplicates()
    
        # Tri par date si disponible
        if 'date' in df.columns:
            df = df.sort_values('date', ascending=False)
    
        return df
    
    def get_data_summary(df):
        """Génère un résumé statistique des données"""
        summary = {
            'total_rows': len(df),
            'total_columns': len(df.columns),
            'date_range': None,
            'regions': [],
            'memory_usage': df.memory_usage(deep=True).sum() / 1024**2  # MB
        }
    
        # Plage de dates
        if 'date' in df.columns:
            summary['date_range'] = (df['date'].min(), df['date'].max())
    
        # Régions uniques
        if 'region' in df.columns:
            summary['regions'] = df['region'].unique().tolist()
    
        return summary
    # Dans data_loader.py
    
    def calculate_regularite(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calcule le taux de régularité à partir des colonnes disponibles
        
        Args:
            df: DataFrame TER
            
        Returns:
            DataFrame avec la colonne taux_regularite ajoutée
        """
        df = df.copy()
        
        # Méthode 1 : Si on a "nombre_trains_a_l_heure"
        if 'nombre_trains_a_l_heure' in df.columns and 'nombre_trains_circules' in df.columns:
            df['taux_regularite'] = (
                df['nombre_trains_a_l_heure'] / df['nombre_trains_circules'] * 100
            ).fillna(0)
            print("✅ Taux de régularité calculé à partir de 'nombre_trains_a_l_heure'")
        
        # Méthode 2 : Si on a "nombre_trains_retard"
        elif 'nombre_trains_retard' in df.columns and 'nombre_trains_circules' in df.columns:
            df['taux_regularite'] = (
                100 - (df['nombre_trains_retard'] / df['nombre_trains_circules'] * 100)
            ).fillna(0)
            print("✅ Taux de régularité calculé à partir de 'nombre_trains_retard'")
        
        # Méthode 3 : Si on a un pourcentage de régularité direct
        elif 'regularite' in df.columns:
            df['taux_regularite'] = df['regularite']
            print("✅ Colonne 'regularite' renommée en 'taux_regularite'")
        
        # Méthode 4 : Chercher une colonne contenant "regularite" ou "ponctualite"
        else:
            regularite_cols = [col for col in df.columns if 'regularite' in col.lower() or 'ponctualite' in col.lower()]
            
            if regularite_cols:
                df['taux_regularite'] = df[regularite_cols[0]]
                print(f"✅ Colonne '{regularite_cols[0]}' utilisée comme taux_regularite")
            else:
                print("⚠️ Impossible de calculer le taux de régularité. Colonnes disponibles :")
                print(df.columns.tolist())
                # Valeur par défaut
                df['taux_regularite'] = 0
        
        # S'assurer que les valeurs sont entre 0 et 100
        df['taux_regularite'] = df['taux_regularite'].clip(0, 100)
        
        return df
    
    def load_data(self) -> pd.DataFrame:
        """
        Charge les données TER depuis l'API
        
        Returns:
            DataFrame avec les données TER et le taux de régularité calculé
        """
        url = "https://ressources.data.sncf.com/api/explore/v2.1/catalog/datasets/regularite-mensuelle-ter/records"
        
        params = {
            'limit': 100,
            'offset': 0
        }
        
        all_records = []
        
        print("📥 Téléchargement des données TER...")
        
        while True:
            try:
                response = requests.get(url, params=params, timeout=30)
                response.raise_for_status()
                
                data = response.json()
                records = data.get('results', [])
                
                if not records:
                    break
                
                all_records.extend(records)
                print(f"  → {len(all_records)} enregistrements téléchargés...")
                
                if len(records) < params['limit']:
                    break
                
                params['offset'] += params['limit']
                
            except requests.exceptions.RequestException as e:
                print(f"❌ Erreur lors du téléchargement : {e}")
                break
        
        if not all_records:
            raise ValueError("❌ Aucune donnée téléchargée")
        
        # Créer le DataFrame
        df = pd.DataFrame(all_records)
        
        print(f"✅ {len(df)} enregistrements chargés")
        print(f"📊 Colonnes disponibles : {', '.join(df.columns.tolist()[:10])}...")
        
        # Nettoyage de base
        df = self._clean_data(df)
        
        # NOUVEAU : Calculer le taux de régularité
        df = self.calculate_regularite(df)
        
        return df
    
    def _clean_data(self, df: pd.DataFrame) -> pd.DataFrame:
        """Nettoie et prépare les données"""
        df = df.copy()
        
        # Convertir les dates
        date_columns = ['date', 'mois', 'annee']
        for col in date_columns:
            if col in df.columns:
                if col == 'date':
                    df[col] = pd.to_datetime(df[col], errors='coerce')
        
        # Convertir les colonnes numériques
        numeric_columns = [
            'nombre_trains_prevus', 'nombre_trains_circules',
            'nombre_trains_supprimes', 'nombre_trains_retard',
            'nombre_trains_a_l_heure'
        ]
        
        for col in numeric_columns:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors='coerce')
        
        # Supprimer les lignes avec dates invalides
        if 'date' in df.columns:
            df = df.dropna(subset=['date'])
        
        return df    
